# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: NOW UK
    url: https://help.nowtv.com/
  - name: NOW IE
    url: https://help.nowtv.com/ie/
  - name: NOW IT
    url: https://www.nowtv.it/assistenza/
  - name: WOW DE
    url: https://www.wowtv.de/hilfe
  - name: Sky X
    url: https://skyx.sky.at/hilfe/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /gsp-eu
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GSP Customer Management Uptime
  introTitle: EU Uptime
  introMessage: xxxxx
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
